### ISSUE TITLE
Traceback Error

### ISSUE THREAD

**Issue by samsonrosen** [davorf/BlackBeanControl#7] opened 2016-12-13 02:19 UTC
Hello!

Firstly, your documentation and plugin is great! I am using it in conjunction with Homebridge so I can control the RM3 via Siri which is excellent.

My RM3 controls my Amp, TV and AppleTV - however when a command is sent my AppleTV (long menu hold) I get this error:

```
bash-3.2# python /Users/churchserver/python-broadlink/BlackBeanControl/BlackBeanControl.py -c WakeATV
Traceback (most recent call last):
  File "/Users/churchserver/python-broadlink/BlackBeanControl/BlackBeanControl.py", line 170, in <module>
    RM3Device.send_data(FinalCommand)
  File "/Library/Python/2.7/site-packages/broadlink-0.2-py2.7.egg/broadlink/__init__.py", line 376, in send_data
    self.send_packet(0x6a, packet)
  File "/Library/Python/2.7/site-packages/broadlink-0.2-py2.7.egg/broadlink/__init__.py", line 235, in send_packet
    response = self.cs.recvfrom(1024)
socket.timeout: timed out
bash-3.2# 
```

The command is sent, and the AppleTV responds. This doesn't to happen with other two devices. My ini file looks like this:

```
[General]
IPAddress = 192.168.1.204
Port = 80
MACAddress = B4:43:0D:FB:FD:A5
Timeout = 10

[Commands]
PowerAmplifier = 7f40ecac678f67dd9c236cebdc0c69be999fd7f85ee1f585d9ddf18e6d609b49580bc3b8db12a976b76ce74ea4c452670e5aa4ad7f54732caff046ae144a59a392075805c902c25aa6a0d53d9336a54fca2ba6bea0695905cd97ff02be79ae2a2bf39829d033aa0ec8ac456cee5041af
PowerToshiba = 78cbb8bf2d6b795f8f80e1085fe32f52378d0a5bc4ee135d9865dc4dd5c16c91685d24add25dc56dae6c2f2112f2956cedb3f1a100359e3ee811e7d68fd5337d
WakeATV = dc4b1cdf001be54b732ab8b0196a123f8d84eb3ae0e2600882db488a88ff882214e90b59b6b6928dcc5824090228aea6725faca794ead38367d7327065c4a0d746277dd6ff71b80c00102f93d31241f7c94f935a8a25fa7b58c5ebbe4f4a28179bbbbae751f5c9b4802a485351485b4a8c5e1901f18511606c7938850e93965f42935defb43deb6c2a01ae2bb4e94600429352efb43deb6f2a01a12bb4e94600a01ec92be7264b08bdccc80d4ba3405120cee09d1511fa9e91fc1267b2460464dcef51f0e192c11361543385b8aea0ba20cee09d1311fa9c91fc1260b7460466cf73ceb7fde6f18e8d0286664b33ef94440bbf0dcb0000cfd42e768b5b683d825d1f45815e9658249ecb90c62d2be8f132a85ea226f2b3714d86e7f15913ce48391515e372193047c21c43ff9f15e8d3
MuteTV = 278c739e7f03d9e997bc71d8d437130839d7402131e9f435d9b2615def7d24e431a578bd2e14e9b78dc2aeeb6e6eed87d81da3275d17c83af77b3d3976add06c055a22efd9917563446ef34719bfebc137eea49ef8e90464f838418247cfe7673fbdc7993c91a1be0447953ce536105bd5a3bdfcf593374795096ab8e2bc8e9b
MuteAmp = bff374eea689a8410c63b62d11ca9ba828029c1520ae83878a3801d4f15884abd85d0c2d873609a8a96f98f5afcdb1f43da128eca44efc05c5f9b5e943aff76629d38507e366ba0364bc7162956b4e5a19020c40be2c2819630d4ef135b0cae7
```

This does not disrupt my usage, but it is just a bit confusing why the error appears.

Thanks,

Sam

**Comment by davorf** [comment] 2016-12-13 14:20
Hello!

Does this error appears when the device is in learning mode, or when it's sending IR command? I've tried to reproduce this behavior, but couldn't. I haven't had time to check if python-broadlink package has changed. Maybe that's the reason I'm not getting any errors and you do. If I manage to find a source of the error, I'll report it here.

Best regards,
Davor

**Comment by davorf** [comment] 2017-01-04 14:35
Hello! 

Since there is no new information regarding this issue, I will close it. If you still have the same problem, feel free to open a new issue.

Best regards,
Davor

**Closed as completed by davorf** 2017-01-04 14:35 UTC
